export const shoes = [
  {
    id: 1,
    name: "Air Max 90",
    brand: "Nike",
    price: 129.99,
    rating: 4.5,
    size: "9",
    image: "/shoes/s1.png",
  },
  {
    id: 2,
    name: "UltraBoost",
    brand: "Adidas",
    price: 149.99,
    rating: 4.7,
    size: "10",
    image: "/shoes/s2.png",
  },
  {
    id: 3,
    name: "Gel-Kayano",
    brand: "ASICS",
    price: 119.99,
    rating: 4.3,
    size: "8.5",
    image: "/shoes/s3.png",
  },
  {
    id: 4,
    name: "Classic Leather",
    brand: "Reebok",
    price: 89.99,
    rating: 4.2,
    size: "9.5",
    image: "/shoes/s4.png",
  },
  {
    id: 5,
    name: "Chuck Taylor",
    brand: "Converse",
    price: 74.99,
    rating: 4.6,
    size: "8",
    image: "/shoes/s5.png",
  },
  {
    id: 6,
    name: "Old Skool",
    brand: "Vans",
    price: 69.99,
    rating: 4.4,
    size: "7.5",
    image: "/shoes/s6.png",
  },
  {
    id: 7,
    name: "ZoomX Vaporfly",
    brand: "Nike",
    price: 199.99,
    rating: 4.8,
    size: "10",
    image: "/shoes/s7.png",
  },
  {
    id: 8,
    name: "Future Rider",
    brand: "Puma",
    price: 99.99,
    rating: 4.1,
    size: "9",
    image: "/shoes/s8.png",
  },
  {
    id: 9,
    name: "FuelCell Rebel",
    brand: "New Balance",
    price: 139.99,
    rating: 4.6,
    size: "8.5",
    image: "/shoes/s9.png",
  },
  {
    id: 10,
    name: "Wave Rider",
    brand: "Mizuno",
    price: 109.99,
    rating: 4.3,
    size: "7",
    image: "/shoes/s10.png",
  },
];